[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 4000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"